name: Nuget Search

on:   
  [workflow_dispatch]

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/during-migration-nuget-3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Nuget Get repo package Version
        run: |
           curl -v -k -X GET https://nuget.pkg.github.com/during-migration-nuget-3/download/nuget-1/index.json  -H "AUTHORIZATION: bearer ${{secrets.GITHUB_TOKEN}}"
      - name: Nuget Get non-repo private package Version
        run: |
           curl -v -k -X GET https://nuget.pkg.github.com/during-migration-nuget-3/download/nuget-2/index.json  -H "AUTHORIZATION: bearer ${{secrets.GITHUB_TOKEN}}"
 
      - name: Nuget Get internal package Version
        run: |
           curl -v -k -X GET https://nuget.pkg.github.com/during-migration-nuget-3/download/nuget-local-v2/index.json  -H "AUTHORIZATION: bearer ${{secrets.GITHUB_TOKEN}}"
           
      - name: Nuget Get public package Version
        run: |
           curl -v -k -X GET https://nuget.pkg.github.com/during-migration-nuget-3/download/nuget-3/index.json  -H "AUTHORIZATION: bearer ${{secrets.GITHUB_TOKEN}}"
     
